#!/usr/bin/env ruby

files = %w[
  .bash_profile
  .gemrc
  .gitconfig
  .pryrc
  .irbrc
  .zshrc
  .agignore
  .ssh/config
]

files.each do |file|
  puts "symlinking #{file}"
  `rm -f $HOME/#{file}`
  `ln ./#{file} $HOME/#{file}`
end

conf = '.gnupg/gpg.conf'
puts "symlinking #{conf}"
`rm -f $HOME/#{conf}`
`ln ./#{conf} $HOME/#{conf}`
puts 'dont forget to write passphrase to /Users/morr/.gnupg/passphrase'

puts 'done!'
