#!/usr/bin/env ruby

files = %w[
  .bash_profile
  .gemrc
  .gitconfig
  .pryrc
  .irbrc
  .zshrc
  .agignore
  .ssh/config
]

files.each do |file|
  puts "symlinking #{file}"
  `rm -f $HOME/#{file}`
  `ln ./#{file} $HOME/#{file}`
end

puts 'done!'
