require("config.options")
require("config.mappings")
require("config.lsp_mappings")
require("config.autocmds")
require("config.utils")
require("config.ai")
require("config.syntax")
require("config.lazy")
